services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: oppradar
    ports:
      - "5432:5432"

  webserver:
    build: .
    restart: always
    depends_on: [db]
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=${DATABASE_URL}
      - AIRFLOW__WEBSERVER__BASE_URL=http://localhost:8000
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/airflow_home/dags
    ports:
      - "8000:8080"
    volumes:
      - ./airflow_home:/opt/airflow/airflow_home
      - ./src:/opt/airflow/src
    command: >
      bash -c "airflow db upgrade &&
              exec airflow webserver"
  scheduler:
    build: .
    restart: always
    depends_on: [webserver]
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=${DATABASE_URL}
    volumes:
      - ./airflow_home:/opt/airflow/airflow_home
      - ./src:/opt/airflow/src
    command: airflow scheduler
