services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: oppradar
    ports:
      - "5432:5432"

  webserver:
    build: .
    restart: always
    depends_on: [db]
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=${DATABASE_URL}
    ports:
      - "8080:8080"
    volumes:
      - .:/opt/airflow
    command: >
      bash -c "airflow db upgrade &&
               airflow users create --username admin --firstname Admin --lastname User \
                 --role Admin --email admin@example.com --password admin &&
               airflow webserver"
  scheduler:
    build: .
    restart: always
    depends_on: [webserver]
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=${DATABASE_URL}
    volumes:
      - .:/opt/airflow
    command: airflow scheduler
